### ISSUE TITLE
Installer no longer functional - Expired cert

### ISSUE THREAD

**Issue by henk717** [timminator/Virtual-Display-Driver#1]
The certificate used in the installer has expired and your install method is certificate sensitive.
As a result an unknown device is created with no corresponding driver.

Installing the driver with an altered time can be done as a workaround, I recommend publishing a new version with a certificate date far in the future such as 2050.

**Comment by timminator** [comment]
Yes, I noticed this issue aswell. The certificate expired in the middle of october.
But I already updated the assets of my release with a renewed certificate some time ago.
The new executables have the valid certificate now.
I didn't make a new release to keep compatibility with my other project that relies on this one. I know thats not the best practice, sorry for the inconvenience.
So you just need to redownload the new executable to get it working again.
And thank you for using my installer. :-)
